### ISSUE TITLE
关于双白色的解释疑问

### ISSUE THREAD

**Issue by pkxpp** [lichuang/Lua-Source-Internal#10]
结贴！！！自己看错了，最后说明一下。

> “然而,即使是这样,却仍然有另一个没有解决的问题.从上面的算法可以看出,没有被引用的对象其颜色在一个扫描过程中始终保持不变为白色,那么假如一个对象在一个GC过程的标记阶段之后被创建,根据前面对颜色的描述,它应该是白色的,这样在紧跟着的回收阶段,这个对象就会在没有被扫描标记的情况下被认为是没有被引用的对象而删除.因此,Lua除了前面的三色概念之外,又细分出来一个"双白色"的概念.简单的说,Lua中的白色分为"当前白色(currentwhite)"和"非当前白色(otherwhite)",这两种白色的状态交替使用,第N次GC使用的是第一种白色,那么下一次就是另外一种,以此类推,代码在回收时候会做判断,如果某个对象的白色不是此次GC回收使用的白色状态将不会被认为是没有被引用的对象而回收,这样的白色对象将留在下一次GC中进行扫描,因为在下一次GC中上一次幸免的白色将成为这次的回收颜色.”

我觉得您的说法有点问题：
* 在当前gc流程中，new出来的可以被释放的GCOjbect是被标记为currentwhite的
* 在当前gc流程中，没有被处理的ojbect应该是上一轮gc流程中设置的白色，即otherwhite
* 在当前gc流程中的sweep阶段，也是会清理叼上一轮的白色（即otherwhite）的GCObject
* 所以，您在这里说的“如果某个对象的白色不是此次GC回收使用的白色状态将不会被认为是没有被引用的对象而回收,这样的白色对象将留在下一次GC中进行扫描”我觉得是不对的

sweep的代码(如果是deadmask（otherwhite）就会进入else逻辑，从而freeobj)：
```
   int deadmask = otherwhite(g);
   // 循环省略...
   if ((curr->gch.marked ^ WHITEBITS) & deadmask) {  /* not dead? */
         lua_assert(!isdead(g, curr) || testbit(curr->gch.marked, FIXEDBIT));
         makewhite(g, curr);  /* make it white (for next cycle) */
         p = &curr->gch.next;
       }
       else {  /* must erase `curr' */
         lua_assert(isdead(g, curr) || deadmask == bitmask(SFIXEDBIT));
         *p = curr->gch.next;
         if (curr == g->rootgc)  /* is the first element of the list? */
           g->rootgc = curr->gch.next;  /* adjust first */
         freeobj(L, curr);
       }
     }
```

---

补充说明：
在atomic最后，会切换白色，也就是currentwhite变成了otherwhite，而otherwhite变成了currentwhite。说明了从在这个时间点，全部扫描完之后，如果仍然是白色的节点在接下来的sweep会被清理掉，而之后的白色不会被清理掉，说明如下：
* sweeplist的代码很清除，依旧是清理otherwhite，说明是atomic处理完之后还是白色的节点
* 扫描阶段（propagatemark）是可以中断的，而这个过程中新增加的白色对象最终都会挂到gray链表上，所以不用担心因为白色被清理掉
* sweep阶段也是可以中断的，所以在这个阶段新增加的对象是currentwhite，所以在sweeplist函数中是不会被清理掉的

**Comment by lichuang** [comment]
抱歉回复的晚了，还是感谢你看的这么仔细。
