### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by teijinyer** [lichuang/Lua-Source-Internal#4]
我是个初学者
关于第二章 基础数据结构中的Lua表中的：以上代码创建了一个Lua表,向其中添加了key分别为1和100的两条记录,最后通过ipairs打印出其数组部分的key分别是什么,但是最后的输出只有1这一个key,可见100在这里并没有落入数组中.，这个似乎是错误的，我测试过我能够输出t[100]为0，查了下ipairs当得出数据为nil时，则停止。

**Comment by lichuang** [comment]
不好意思,回复的晚了,实在太忙.这里的意思,并不是t[100]这个数据没有了,而是通过ipairs遍历这个table的数组部分并不能拿到这个数据,想说明的是这个情况下t[100]不在数组部分,而是在hash.
